In [ ]:
import pandas as pd
from google.colab import drive
import io
from google.colab import files
import numpy as np


In [ ]:
uploaded = files.upload()


Saving raw_data.xlsx to raw_data.xlsx


In [ ]:
df = pd.read_excel(io.BytesIO(uploaded.get('raw_data.xlsx')))
df.head(15)

Disease  Count of Disease Occurrence  \
0   UMLS:C0020538_hypertensive disease                       3363.0   
1                                  NaN                          NaN   
2                                  NaN                          NaN   
3                                  NaN                          NaN   
4                                  NaN                          NaN   
5                                  NaN                          NaN   
6                                  NaN                          NaN   
7                                  NaN                          NaN   
8                                  NaN                          NaN   
9                                  NaN                          NaN   
10                                 NaN                          NaN   
11                                 NaN                          NaN   
12              UMLS:C0011847_diabetes                       1421.0   
13                                 NaN                          NaN   
14                                 NaN                          NaN   

                                              Symptom  
0                            UMLS:C0008031_pain chest  
1                   UMLS:C0392680_shortness of breath  
2                             UMLS:C0012833_dizziness  
3                              UMLS:C0004093_asthenia  
4                                  UMLS:C0085639_fall  
5                               UMLS:C0039070_syncope  
6                               UMLS:C0042571_vertigo  
7   UMLS:C0038990_sweat^UMLS:C0700590_sweating inc...  
8                           UMLS:C0030252_palpitation  
9                                UMLS:C0027497_nausea  
10                      UMLS:C0002962_angina pectoris  
11                       UMLS:C0438716_pressure chest  
12                             UMLS:C0032617_polyuria  
13                           UMLS:C0085602_polydypsia  
14                  UMLS:C0392680_shortness of breath

In [ ]:
df = df.fillna(method='ffill')
df.head(15)

Disease  Count of Disease Occurrence  \
0   UMLS:C0020538_hypertensive disease                       3363.0   
1   UMLS:C0020538_hypertensive disease                       3363.0   
2   UMLS:C0020538_hypertensive disease                       3363.0   
3   UMLS:C0020538_hypertensive disease                       3363.0   
4   UMLS:C0020538_hypertensive disease                       3363.0   
5   UMLS:C0020538_hypertensive disease                       3363.0   
6   UMLS:C0020538_hypertensive disease                       3363.0   
7   UMLS:C0020538_hypertensive disease                       3363.0   
8   UMLS:C0020538_hypertensive disease                       3363.0   
9   UMLS:C0020538_hypertensive disease                       3363.0   
10  UMLS:C0020538_hypertensive disease                       3363.0   
11  UMLS:C0020538_hypertensive disease                       3363.0   
12              UMLS:C0011847_diabetes                       1421.0   
13              UMLS:C0011847_diabetes                       1421.0   
14              UMLS:C0011847_diabetes                       1421.0   

                                              Symptom  
0                            UMLS:C0008031_pain chest  
1                   UMLS:C0392680_shortness of breath  
2                             UMLS:C0012833_dizziness  
3                              UMLS:C0004093_asthenia  
4                                  UMLS:C0085639_fall  
5                               UMLS:C0039070_syncope  
6                               UMLS:C0042571_vertigo  
7   UMLS:C0038990_sweat^UMLS:C0700590_sweating inc...  
8                           UMLS:C0030252_palpitation  
9                                UMLS:C0027497_nausea  
10                      UMLS:C0002962_angina pectoris  
11                       UMLS:C0438716_pressure chest  
12                             UMLS:C0032617_polyuria  
13                           UMLS:C0085602_polydypsia  
14                  UMLS:C0392680_shortness of breath

In [ ]:
df['Disease'] = df['Disease'].str.split('_').str[-1]
df['Symptom'] = df['Symptom'].str.split('_').str[-1]

In [ ]:
df.head()

Disease  Count of Disease Occurrence              Symptom
0  hypertensive disease                       3363.0           pain chest
1  hypertensive disease                       3363.0  shortness of breath
2  hypertensive disease                       3363.0            dizziness
3  hypertensive disease                       3363.0             asthenia
4  hypertensive disease                       3363.0                 fall

In [ ]:
df.replace(float('nan'), np.nan, inplace=True)
df.dropna(inplace=True)

In [ ]:
#Model Training
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier, export_graphviz

In [ ]:

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

label_encoder = LabelEncoder()


In [ ]:
integer_encoded = label_encoder.fit_transform(df['Symptom'])
print(integer_encoded)


[253 324  85 ... 356 128 120]


In [ ]:
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [ ]:
cols = np.asarray(df['Symptom'].unique())
cols

array(['pain chest', 'shortness of breath', 'dizziness', 'asthenia',
       'fall', 'syncope', 'vertigo', 'sweating increased', 'palpitation',
       'nausea', 'angina pectoris', 'pressure chest', 'polyuria',
       'polydypsia', 'orthopnea', 'rale', 'unresponsiveness',
       'mental status changes', 'vomiting', 'labored breathing',
       'feeling suicidal', 'suicidal', 'hallucinations auditory',
       'feeling hopeless', 'weepiness', 'sleeplessness',
       'motor retardation', 'irritable mood', 'blackout',
       'mood depressed', 'hallucinations visual', 'worry', 'agitation',
       'tremor', 'intoxication', 'verbal auditory hallucinations',
       'energy increased', 'difficulty', 'nightmare',
       'unable to concentrate', 'homelessness', 'hypokinesia',
       'dyspnea on exertion', 'chest tightness', 'cough', 'fever',
       'decreased translucency', 'productive cough', 'pleuritic pain',
       'yellow sputum', 'breath sounds decreased', 'chill', 'rhonchus',
       'green spu

In [ ]:
df_ohe = pd.DataFrame(columns = cols)
df_ohe.head()

Empty DataFrame
Columns: [pain chest, shortness of breath, dizziness, asthenia, fall, syncope, vertigo, sweating increased, palpitation, nausea, angina pectoris, pressure chest, polyuria, polydypsia, orthopnea, rale, unresponsiveness, mental status changes, vomiting, labored breathing, feeling suicidal, suicidal, hallucinations auditory, feeling hopeless, weepiness, sleeplessness, motor retardation, irritable mood, blackout, mood depressed, hallucinations visual, worry, agitation, tremor, intoxication, verbal auditory hallucinations, energy increased, difficulty, nightmare, unable to concentrate, homelessness, hypokinesia, dyspnea on exertion, chest tightness, cough, fever, decreased translucency, productive cough, pleuritic pain, yellow sputum, breath sounds decreased, chill, rhonchus, green sputum, non-productive cough, wheezing, haemoptysis, distress respiratory, tachypnea, malaise, night sweat, jugular venous distention, dyspnea, dysarthria, speech slurred, facial paresis, hemiplegia, seizure, numbness, symptom aggravating factors, st segment elevation, st segment depression, t wave inverted, presence of q wave, chest discomfort, bradycardia, pain, nonsmoker, erythema, hepatosplenomegaly, pruritus, diarrhea, abscess bacterial, swelling, apyrexial, dysuria, hematuria, renal angle tenderness, lethargy, hyponatremia, hemodynamically stable, difficulty passing urine, consciousness clear, guaiac positive, monoclonal, ecchymosis, tumor cell invasion, haemorrhage, pallor, fatigue, ...]
Index: []

[0 rows x 399 columns]

In [ ]:
for i in range(len(onehot_encoded)):
    df_ohe.loc[i] = onehot_encoded[i]
df_ohe.head()

pain chest  shortness of breath  dizziness  asthenia  fall  syncope  \
0         0.0                  0.0        0.0       0.0   0.0      0.0   
1         0.0                  0.0        0.0       0.0   0.0      0.0   
2         0.0                  0.0        0.0       0.0   0.0      0.0   
3         0.0                  0.0        0.0       0.0   0.0      0.0   
4         0.0                  0.0        0.0       0.0   0.0      0.0   

   vertigo  sweating increased  palpitation  nausea  ...  feces in rectum  \
0      0.0                 0.0          0.0     0.0  ...              0.0   
1      0.0                 0.0          0.0     0.0  ...              0.0   
2      0.0                 0.0          0.0     0.0  ...              0.0   
3      0.0                 0.0          0.0     0.0  ...              0.0   
4      0.0                 0.0          0.0     0.0  ...              0.0   

   prodrome  hypoproteinemia  alcohol binge episode  abdomen acute  \
0       0.0              0.0                    0.0            0.0   
1       0.0              0.0                    0.0            0.0   
2       0.0              0.0                    0.0            0.0   
3       0.0              0.0                    0.0            0.0   
4       0.0              0.0                    0.0            0.0   

   air fluid level  catching breath  large-for-dates fetus  immobile  \
0              0.0              0.0                    0.0       0.0   
1              0.0              0.0                    0.0       0.0   
2              0.0              0.0                    0.0       0.0   
3              0.0              0.0                    0.0       0.0   
4              0.0              0.0                    0.0       0.0   

   homicidal thoughts  
0                 0.0  
1                 0.0  
2                 0.0  
3                 0.0  
4                 0.0  

[5 rows x 399 columns]

In [ ]:
df_concat = pd.concat([df['Disease'],df_ohe], axis=1)
df_concat.head()

Disease  pain chest  shortness of breath  dizziness  asthenia  \
0  hypertensive disease         0.0                  0.0        0.0       0.0   
1  hypertensive disease         0.0                  0.0        0.0       0.0   
2  hypertensive disease         0.0                  0.0        0.0       0.0   
3  hypertensive disease         0.0                  0.0        0.0       0.0   
4  hypertensive disease         0.0                  0.0        0.0       0.0   

   fall  syncope  vertigo  sweating increased  palpitation  ...  \
0   0.0      0.0      0.0                 0.0          0.0  ...   
1   0.0      0.0      0.0                 0.0          0.0  ...   
2   0.0      0.0      0.0                 0.0          0.0  ...   
3   0.0      0.0      0.0                 0.0          0.0  ...   
4   0.0      0.0      0.0                 0.0          0.0  ...   

   feces in rectum  prodrome  hypoproteinemia  alcohol binge episode  \
0              0.0       0.0              0.0                    0.0   
1              0.0       0.0              0.0                    0.0   
2              0.0       0.0              0.0                    0.0   
3              0.0       0.0              0.0                    0.0   
4              0.0       0.0              0.0                    0.0   

   abdomen acute  air fluid level  catching breath  large-for-dates fetus  \
0            0.0              0.0              0.0                    0.0   
1            0.0              0.0              0.0                    0.0   
2            0.0              0.0              0.0                    0.0   
3            0.0              0.0              0.0                    0.0   
4            0.0              0.0              0.0                    0.0   

   immobile  homicidal thoughts  
0       0.0                 0.0  
1       0.0                 0.0  
2       0.0                 0.0  
3       0.0                 0.0  
4       0.0                 0.0  

[5 rows x 400 columns]

In [ ]:
df_concat = df_concat.groupby('Disease').sum()
df_concat = df_concat.reset_index()

In [ ]:
X = df_concat[cols]
# Labels
y = df_concat['Disease']

In [ ]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [ ]:
len(y_train)


107

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
clf = LogisticRegression()
clf.fit(X_train, y_train)
clf.score(X, y)


0.7985074626865671

In [ ]:
dt = DecisionTreeClassifier()
clf_dt=dt.fit(X_train, y_train)
clf_dt.score(X, y)

0.7985074626865671

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
clf_nb=gnb.fit(X_train, y_train)
clf_nb.score(X, y)

0.7985074626865671

In [ ]:
from sklearn.ensemble import RandomForestClassifier
# Instantiate model with 1000 decision trees
rf = RandomForestClassifier(n_estimators = 1000, random_state = 42)
clf_rf = rf.fit(X_train, y_train)
clf_rf.score(X,y)

0.7985074626865671

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
clf_gb = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,max_depth=1, random_state=0).fit(X_train, y_train)
clf_gb.score(X,y)

0.7985074626865671

In [ ]:
from sklearn import svm
clf_svm = svm.SVC()
clf_svm.fit(X_train, y_train)
clf_svm.score(X,y)

0.7985074626865671

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
clf_knn = KNeighborsClassifier(n_neighbors=3)
clf_knn.fit(X_train, y_train)
clf_knn.score(X,y)

0.2835820895522388

In [ ]:
from sklearn.neural_network import MLPClassifier
clf_nn = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1)
clf_nn.fit(X_train, y_train)
clf_nn.score(X,y)


/usr/local/lib/python3.9/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:541: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


0.19402985074626866